In [1]:
# Linear Alebra
import numpy as np

a = np.array([[1.0,2.0],[3.0,4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [2]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [3]:
a.T

array([[1., 3.],
       [2., 4.]])

In [4]:
# matriz inversa
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
# matriz identidade nxn
n = 2
np.eye(n)

array([[1., 0.],
       [0., 1.]])

In [6]:
n = 10
np.eye(n)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

$A.A^{-1} = I$

In [7]:
# multiplicacao de matriz
np.dot(a, np.linalg.inv(a)) # ~I

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [8]:
# autovalores e autovetores, respectivamente
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [9]:
# Exercicio :
# regressão linear - dados pontos encontrar a melhor reta que junto todos os valores 
# (método dos mininos quadrados)

Formula do cálculo: $w = (X^{T}X)^{-1}X^{T}y$

In [ ]:
"""
X é a matriz que representa nosso conjuntos de pontos (cada linha é um vetor multidimensional que representa um ponto
    no espaço n-D)
y é o valor desse ponto

Portanto, o objetivo é implementar uma função que retorne o vetor de coefientes w.
"""

In [11]:
X = np.abs(np.random.normal(60,500,100))[:, np.newaxis]
w = 2000
y = X * (w - np.random.normal(0,100,X.shape[0]))[:, np.newaxis]

Formula da Reta: $y = b + ax$

In [12]:
def ajustar(X, y):
    return np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

ajustar(X,y)

array([[2003.10419243]])