In [16]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.arange(7,10)

print("a : ",a)
print("b : ",b)
print("c : ",c)

a :  [1 2 3]
b :  [4 5 6]
c :  [7 8 9]


In [3]:
#concatenar
print(np.concatenate((a,b)))
print(np.concatenate((b,a)))

[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [4]:
print(np.concatenate((a, b, c)))

[1 2 3 4 5 6 7 8 9]


In [21]:
np.concatenate([a, b, c])

#np.concatenate(a, b, c) # forma errada de concatenar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# concatenando matrizes
a = np.floor(10 * np.random.random((2,2)))
print(a)

print("----")

b = np.floor(10 * np.random.random((2,2)))
print(b)

[[9. 6.]
 [7. 1.]]
----
[[9. 7.]
 [3. 5.]]


In [25]:
# equivale ao np.vstack((a, b))
print(np.concatenate((a,b), axis=0))

print("----")

# equivale ao np.hstack((a, b))
print(np.concatenate((a,b), axis=1))

[[9. 6.]
 [7. 1.]
 [9. 7.]
 [3. 5.]]
----
[[9. 6. 9. 7.]
 [7. 1. 3. 5.]]


In [26]:
print(np.vstack((a, b)))
print("----")
print(np.hstack((a, b)))

[[9. 6.]
 [7. 1.]
 [9. 7.]
 [3. 5.]]
----
[[9. 6. 9. 7.]
 [7. 1. 3. 5.]]


In [40]:
# copias

a = np.arange(12)
print(a)

b = a

# a e b são o mesma instância
print(b is a, id(b), id(a))

b.shape = 3,4 # muda a
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]
True 4441554016 4441554016


(3, 4)

In [32]:
# mesma instância
def f(x):
    print(id(x))
    
print(id(a))
f(a)

4441513216
4441513216


In [33]:
# gerando uma cópia
def f(x):
    print(id(x.copy()))
    
print(id(a))
f(a)

4441513216
4441551616


In [41]:
# sclicing com copy (fazer uma view)
s = a[:, 1:3].copy()
s[:] = 10
a

# sclicing sem copy
s = a[:, 1:3]
s[:] = 10
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
# um novo objeto com um novo data é criado
d = a.copy()

print(d is a)
#não compartilha nada com a
print(d.base is a)

d[0,0] = 9999
print(a)
print("---")
print(d)

False
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---
[[9999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
