In [1]:
import numpy as np

series = [[23,45,12,679], [14,48,69,38]]

new_series = np.array(series)

print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [9]:
a = np.zeros(10) + 4
print(a)

a = np.zeros(10) * 4
print(a)

a = np.ones(10) * 4
print(a)

a = np.ones(10) + 4
print(a)

a = 4
print(a)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
4


In [10]:
import numpy as np
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


In [11]:
import numpy as np

percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype)

float64


In [18]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr % 2).astype(bool)] = -1
print(arr)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2] = -1
print(arr)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2] = -1
print(arr)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 0] = -1
print(arr)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[np.arange(0, arr.shape[0], 2)] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[-1  1 -1  3 -1  5 -1  7 -1  9]
[-1  1 -1  3 -1  5 -1  7 -1  9]
[-1  1 -1  3 -1  5 -1  7 -1  9]


In [35]:
arr = np.array([80, 10, 50, 30])

def normaliza(arr):
    #return arr / arr.min() # errado
    #return arr / arr.max() # certo
    #return (arr - arr.min()) / (arr.max() - arr.min())  # certo
    #return arr / arr.sum() # certo 
           # o que deve ser retornado
           # para que os valores de arr
           # fiquem compreendido entre 0 e 1

print(normaliza(arr))

[8. 1. 5. 3.]


In [31]:
import numpy as np

# qual faz média ponderada

valores = np.array([80, 10, 50, 30])
pesos = np.array([2, 5, 1, 1])

print(np.average(valores, weights=pesos)) # certo
print(np.mean(valores * pesos)) # errado
print(np.sum(valores * pesos) / np.sum(pesos)) # certo
print(np.average(valores * pesos)) # errado
print(np.sum(valores * pesos) / valores.shape[0]) # errado

32.22222222222222
72.5
32.22222222222222
72.5
72.5
