In [6]:
import numpy as np

a = np.arange(10) ** 2

print(a)

print(a[4])

print(a[5:])

print(a[::2]) # de 2 em dois

print(a[::-1]) # invertendo

[ 0  1  4  9 16 25 36 49 64 81]
16
[25 36 49 64 81]
[ 0  4 16 36 64]
[81 64 49 36 25 16  9  4  1  0]


In [17]:
a = (np.arange(16) ** 2).reshape((4,4))

print(a)

print(a[0,1]) #elemento da linha 0 e coluna 1

print(a[:3,0]) # elementos da linha 0 a 2 da coluna 0

print(a[:,0]) # todos elementos da coluna 0

print(a[:,:2])

print(a[:1,:])

print(a[-1]) #equivalente a a[-1,:]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
1
[ 0 16 64]
[  0  16  64 144]
[[  0   1]
 [ 16  25]
 [ 64  81]
 [144 169]]
[[0 1 4 9]]
[144 169 196 225]


In [21]:
#linha a linha
for linha in a:
    print(linha)
    
print("---------")    

#coluna a coluna
for coluna in a.T:
    print(coluna)

[0 1 4 9]
[16 25 36 49]
[ 64  81 100 121]
[144 169 196 225]
---------
[  0  16  64 144]
[  1  25  81 169]
[  4  36 100 196]
[  9  49 121 225]


In [22]:
# Manipulação do Shape

In [25]:
a = (np.arange(16) ** 2).reshape((4,4))

print(a)

#flattened array - colocar em lista a matriz
print(a.ravel())
print(a.reshape(-1))

#retorna array com novo formato
print(a.reshape(8,2))
print(a.reshape(16,1))
a.shape = (8,2)
print(a)

#transposta
print(a.T)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
[[  0   1]
 [  4   9]
 [ 16  25]
 [ 36  49]
 [ 64  81]
 [100 121]
 [144 169]
 [196 225]]
[[  0]
 [  1]
 [  4]
 [  9]
 [ 16]
 [ 25]
 [ 36]
 [ 49]
 [ 64]
 [ 81]
 [100]
 [121]
 [144]
 [169]
 [196]
 [225]]
[[  0   1]
 [  4   9]
 [ 16  25]
 [ 36  49]
 [ 64  81]
 [100 121]
 [144 169]
 [196 225]]
[[  0   4  16  36  64 100 144 196]
 [  1   9  25  49  81 121 169 225]]


In [30]:
a.ravel() #verificar como está na memoria

print(a.ravel())
a.ravel().reshape((8,2))

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


array([[  0,   1],
       [  4,   9],
       [ 16,  25],
       [ 36,  49],
       [ 64,  81],
       [100, 121],
       [144, 169],
       [196, 225]])

In [31]:
n_nows = 8
n_cols = 2
row = 1
col = 1
a.ravel()[n_cols * row + col]

9

In [36]:
# truques de indexação

a = np.arange(12) ** 2
indices = np.array([1,1,6,3,5])

print(a)

print(a[indices])

bidim_indices = np.array([[1,6], [3,5]])
print(bidim_indices)
print(a[bidim_indices])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1 36  9 25]
[[1 6]
 [3 5]]
[[ 1 36]
 [ 9 25]]


In [42]:
a = (np.arange(21)**2).reshape((7,3))

print(a)

bidim_indices = np. array([[1,0], [2,6]])
print(a[bidim_indices])

a[bidim_indices].shape

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]
 [225 256 289]
 [324 361 400]]
[[[  9  16  25]
  [  0   1   4]]

 [[ 36  49  64]
  [324 361 400]]]


(2, 2, 3)

In [46]:
# tem de ter o mesmo tamanho
id_linhas = np.array([0,1,5])
id_colunas = np.array([2,1,1])

print(a)

print(a[id_linhas, id_colunas])

print(a[:, [0,2]])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]
 [225 256 289]
 [324 361 400]]
[  4  16 256]
[[  0   4]
 [  9  25]
 [ 36  64]
 [ 81 121]
 [144 196]
 [225 289]
 [324 400]]


In [48]:
b = a > 200

print(b)

a[b]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


array([225, 256, 289, 324, 361, 400])

In [50]:
# pode ser util para atribuição
a[b ] = 0
a

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [  0,   0,   0],
       [  0,   0,   0]])