In [3]:
import numpy as np

#criando um ndarray a apartir de uma lista
a = np.array([1, 2, 3, 4, 5, 6])

print(type(a))

# cria um array 2D com 15 elementos de 0 a 14
# com 3 linhas e 5 colunas
b = np.arange(15).reshape(3, 5)

print("a : ", a, "dims: ", a.ndim)
print("b : ", b, "dims: ", b.ndim)

# tipo dos elementso no array
print(a.dtype)

# convertendo para float
print(b.astype(float).dtype)

print(type(a))

<class 'numpy.ndarray'>
a :  [1 2 3 4 5 6] dims:  1
b :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] dims:  2
int64
float64
<class 'numpy.ndarray'>


In [9]:
import numpy as np

# dominancia na criação do array
# str > float > int > bool
a = np.array([2, 3.4, 'Ola'])
print(a, a.dtype)

a = np.array([True, 2, 3.4])
print (a, a.dtype)

a = np.array([True, 2])
print (a, a.dtype)

a = np.array([True, False])
print (a, a.dtype)

a = np.array([2, 3, 4])
print (a, a.dtype)

['2' '3.4' 'Ola'] <U32
[1.  2.  3.4] float64
[1 2] int64
[ True False] bool
[2 3 4] int64


In [14]:
"""
# forma de criar array
a = np.array(1, 2, 3, 4) # errado
"""
a = np.array([1, 2, 3, 4]) # certo

# help da funcção
# np.array?


In [18]:
a = [(1., 0., 0),
     (0., 1., 2.)]
b = np.array(a)
b.ndim

2

In [17]:
a = [(1., 0., 0),
     (0., 1., 2.)]
# explicitamente falando qual é o tipo elementos
b = np.array(a, dtype = complex)
b

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 2.+0.j]])

In [22]:
# array apenas com zeros
# recebe como pagametro o shape
# shape sempre é uma tupla
print(np.zeros((3, 4)))

# array apenas de uns
print(np.ones((3)))

# array não inicializados - perigoso o uso
# (apenas lixos, valores podem sofre alteração)
print(np.empty((1, 2, 10)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1.]
[[[9.38724727e-323 0.00000000e+000 2.46151512e-312 4.82337433e+228
   6.14415221e-144 1.16097020e-028 4.75388684e-038 2.26199768e-076
   2.21378315e-052 3.97062373e+246]
  [1.16318408e-028 1.18948389e-047 6.01642562e-067 3.34426246e-061
   6.18487475e+169 5.04621361e+180 8.37170571e-144 1.62145439e+243
   2.87628517e+180 9.94112800e-143]]]


In [23]:
# array criados com outros valores
print(np.ones((3)) * 10)

[10. 10. 10.]


In [26]:
# array criados com valores rondomicos
10 + np.random.rand(3)

array([10.32492666, 10.51774851, 10.53981409])

In [28]:
# criando sequências de números (arange)
print(np.arange(10, 30, 5))

# também aceita float
print(np.arange(0, 10, 0.5))

[10 15 20 25]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [29]:
# linspace
np.linspace(0, 9.5, 20)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [43]:
# Operações basicas
## array
a = np.array([1, 2, 3])

## escalar
b = 2

print("{} * {} = {}".format(b, a, b * a))
print("{} + {} = {}".format(b, a, b + a))
print("{} - {} = {}".format(b, a, b - a))
print("{} / {} = {}".format(b, a, b / a))
print("{} % {} = {}".format(b, a, b % a))
print("{} ** {} = {}".format(b, a, b ** a))

2 * [1 2 3] = [2 4 6]
2 + [1 2 3] = [3 4 5]
2 - [1 2 3] = [ 1  0 -1]
2 / [1 2 3] = [2.         1.         0.66666667]
2 % [1 2 3] = [0 0 2]
2 ** [1 2 3] = [2 4 8]


In [41]:
# fazendo multiplicação com python em lista - forma mais complexa do que fazer com array
[1, 2, 3] * 2 #resultado errado - neste caso aumentou a lista
[elem * 3 for elem in [1, 2, 3]] #resultado correto mas tive que usar 'for'
list(map(lambda x: x * 3, [1, 2, 3])) #resultado correto mas tive que usar 'map'

[3, 6, 9]

In [44]:
## entre arrays
c = np.array([10, 2, 5])

print("{} * {} = {}".format(a, c, a * c))
print("{} + {} = {}".format(a, c, a + c))
print("{} - {} = {}".format(a, c, a - c))
print("{} / {} = {}".format(a, c, a / c))
print("{} % {} = {}".format(a, c, a % c))
print("{} ** {} = {}".format(a, c, a ** c))

[1 2 3] * [10  2  5] = [10  4 15]
[1 2 3] + [10  2  5] = [11  4  8]
[1 2 3] - [10  2  5] = [-9  0 -2]
[1 2 3] / [10  2  5] = [0.1 1.  0.6]
[1 2 3] % [10  2  5] = [1 0 3]
[1 2 3] ** [10  2  5] = [  1   4 243]


In [45]:
## funções elemento a elemento (element-wise)
print("np.log({}) = {}".format(c, np.log(c)))
print("np.sqrt({}) = {}".format(c, np.sqrt(c)))

np.log([10  2  5]) = [2.30258509 0.69314718 1.60943791]
np.sqrt([10  2  5]) = [3.16227766 1.41421356 2.23606798]


In [48]:
#buscar todas as funções para numpay
np.__dict__

In [55]:
# implementar a métrica Erro Quadrático Médio (MSE)
# $\frac{1}{n}\sum_{i=1}^n (\hat{y_i} - y_i)^2$ (formula em markdown)

def MSE(y_true, y_pred):
    """
    Mean Squared Error
    
    Parametros
    ----------
    y_true : 1d array
        Rótulos.
    y_pred : 1d array
        Predições, retornadas pelo modelo.
    """
    
    n = len(y_true)
    soma = 0
    for i in range(n):
        soma += (y_pred[i] - y_true[i]) ** 2
    
    return soma / n


def vMSE(y_true, y_pred):
    """
    Vectorized Mean Squared Error
    
    Parâmetros
    ----------
    y_true : 1d array
        Rótulos.
    y_pred : 1d array
        Predições, retornadas pelo modelo.
    """
    
    # TODO: versão vetorizada do RMSLE
    
    # primeiro exemplo
    #n = y_true.shape[0]
    #return np.sum((y_pred - y_true) ** 2) / n
    
    # segundo exemplo
    return np.mean((y_pred - y_true) ** 2)

y_true = np.arange(1000000) + 1
y_pred = y_true - np.random.rand(y_true.shape[0])

print(MSE(y_true, y_pred))
print(vMSE(y_true, y_pred))

# para descobrir quando tempo está demorando cada execução no processador
% timeit MSE(y_true, y_pred)
% timeit vMSE(y_true, y_pred)

0.33321013570099056
0.3332101357009778
1.05 s ± 9.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
6.89 ms ± 328 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


$\frac{1}{n}\sum_{i=1}^n (\hat{y_i} - y_i)^2$